services:
  app:
    container_name: mdc-app
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:8080:80"
    environment:
      NODE_ENV: production
      APP_PORT: 80
    env_file: .env
    restart: unless-stopped
