services:
  app:
    container_name: mdc-back
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      APP_PORT: 3000
    env_file: .env
    restart: unless-stopped
